spring:
  application:
    name: playback-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:streamforge_playback}
    username: ${DB_USER:streamforge}
    password: ${DB_PASSWORD:streamforge}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    clean-disabled: false

streamforge:
  catalog-url: ${CATALOG_URL:http://localhost:8091}
  entitlement-url: ${ENTITLEMENT_URL:http://localhost:8092}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
