spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:streamforge_catalog}
    username: ${DB_USER:streamforge}
    password: ${DB_PASSWORD:streamforge}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    clean-disabled: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
